using app.Db.utils;
using app.Models.other.priority;
using app.Services.Common.alias;
using app.Services.PdfReport.Models;
using MigraDoc.DocumentObjectModel;

namespace app.Services.PdfReport
{
	public interface IPdfReportService
	{
		public Task<Document> CreateDocReport((List<ProtocolRequestModel> protocolRequestModel, bool autoGeneratedSchema) protocolInput, Dictionary<string, List<Dictionary<string, object>>> lastSelection, IFormFileCollection files, List<AliasModel> columns, string ruComponentType);
	}
}
