using app.Db.utils;
using app.Models.other.priority;
using app.Services.Common.alias;
using app.Services.PdfReport.Models;
using Microsoft.IdentityModel.Tokens;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Shapes;
using MigraDoc.DocumentObjectModel.Tables;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace app.Services.PdfReport
{
	public class PdfReportService: IPdfReportService
	{
		public async Task<Document> CreateDocReport((List<ProtocolRequestModel> protocolRequestModel, bool autoGeneratedSchema) protocolInput, Dictionary<string, List<Dictionary<string, object>>> selections, IFormFileCollection files, List<AliasModel> columns, string ruComponentType)
		{
			DateTime now = DateTime.Now;
			Document document = new Document();
			Section val = document.AddSection();
			Paragraph val2 = MakeParagraph("ПРОТОКОЛ", (ParagraphAlignment)1, 16, 4, 4);
			Paragraph val3 = MakeParagraph("выбора ЭЭЭ-компонента ", (ParagraphAlignment)1, 14, 48, 8);
			val.Add(val2);
			val.Add(val3);
			Paragraph val4 = MakeParagraph("г. Минск", (ParagraphAlignment)0, 12, 8, 8);
			Paragraph val5 = MakeParagraph(now.ToString("yyyy-MM-dd") + " г", (ParagraphAlignment)2, 12, 8, 8);
			Table val6 = val.AddTable();
			val6.AddColumn("8cm");
			val6.AddColumn("8cm");
			Row val7 = val6.AddRow();
			val7[0].Add(val4);
			val7[1].Add(val5);
			Paragraph val8 = MakeParagraph("Таблица 1 - Содержание базы данных рассматриваемого типа компонента", (ParagraphAlignment)0, 12, 12, 12);
			val.Add(val8);
			Table val9 = val.AddTable();
			val9.Rows.Alignment = (RowAlignment)1;
			val9.Borders.Visible = true;
			val9.AddColumn("4cm");
			val9.AddColumn("8cm");
			val9.AddColumn("4cm");
			Row val10 = val9.AddRow();
			Paragraph val11 = MakeParagraph("№", (ParagraphAlignment)1, 10, 1, 1);
			Paragraph val12 = MakeParagraph("Свойства, содержащиеся в базе данных", (ParagraphAlignment)0, 10, 1, 1);
			Paragraph val13 = MakeParagraph("Значения", (ParagraphAlignment)1, 10, 1, 1);
			val10.Cells[0].Add(val11);
			val10.Cells[1].Add(val12);
			val10.Cells[2].Add(val13);
			val10.Cells[0].VerticalAlignment = (VerticalAlignment)1;
			val10.Cells[1].VerticalAlignment = (VerticalAlignment)1;
			val10.Cells[2].VerticalAlignment = (VerticalAlignment)1;
			Dictionary<int, int> dictionary = new Dictionary<int, int>();
			for (int i = 0; i < columns.Count(); i++)
			{
				ProtocolRequestModel prm = null;
				int num = 1;
				foreach (ProtocolRequestModel item2 in protocolInput.protocolRequestModel)
				{
					if (item2.ParameterName.ToLower() == columns[i].EnVal.ToLower())
					{
						prm = item2;
						break;
					}
					num++;
				}
				Row val14 = val9.AddRow();
				val14.Cells[0].Add(MakeParagraph($"{i + 1}", (ParagraphAlignment)1, 10, 1, 1));
				val14.Cells[1].Add(MakeParagraph(columns[i].RuVal + " / " + columns[i].EnVal, (ParagraphAlignment)0, 10, 1, 1));
				Cell obj = val14.Cells[2];
				val14.Cells[2].Add(MakeParagraph($" {(prm == null ? '-' : prm.ParameterValue)} ", ParagraphAlignment.Center, 10, 1, 1));
				val14.Cells[0].VerticalAlignment = (VerticalAlignment)1;
				val14.Cells[1].VerticalAlignment = (VerticalAlignment)1;
				val14.Cells[2].VerticalAlignment = (VerticalAlignment)1;
				if (prm != null)
				{
					val14.Cells[0].Shading.Color = Colors.PaleGoldenrod;
					val14.Cells[1].Shading.Color = Colors.PaleGoldenrod;
					val14.Cells[2].Shading.Color = Colors.PaleGoldenrod;
					dictionary[num] = i + 1;
				}
			}
			Paragraph val15 = MakeParagraph("Приоритетные характеристики:  ", (ParagraphAlignment)0, 12, 16, 16);
			foreach (int item3 in dictionary.Keys.OrderBy((int x) => x))
			{
				val15.AddFormattedText($"   {dictionary[item3]}   ", (TextFormat)16);
				val15.AddText(";");
			}
			val.Add(val15);
			Section val16 = document.AddSection();
			Paragraph val17 = MakeParagraph("Таблица 2 - Рекомендуемые и принятое ранжирование свойств по степени важности для рассматриваемого компонента космической техники или космической технологии (в порядке убывания от 1-го и выше к менее ответсвенным)", (ParagraphAlignment)0, 12, 12, 12);
			val16.Add(val17);
			Table val18 = val16.AddTable();
			val18.Borders.Width = 0.25;
			val18.Borders.Visible = true;
			val18.AddColumn("4cm");
			val18.AddColumn("8cm");
			val18.AddColumn("4cm");
			Row val19 = val18.AddRow();
			val19[0].Add(MakeParagraph("Ориентировочное", (ParagraphAlignment)1, 10, 1, 1));
			val19[1].Add(MakeParagraph(ruComponentType, (ParagraphAlignment)1, 10, 1, 1));
			val19[2].Add(MakeParagraph("Принятое экспертом", (ParagraphAlignment)1, 10, 1, 1));
			for (int num2 = 0; num2 < columns.Count(); num2++)
			{
				Row val20 = val18.AddRow();
				AliasModel column = columns[num2];
				int priority = 0;
				ProtocolRequestModel protocolRequestModel2 = protocolInput.protocolRequestModel.Where(delegate (ProtocolRequestModel pr, int num11)
				{
					priority = num11 + 1;
					return pr.ParameterName.ToLower() == column.EnVal.ToLower();
				}).FirstOrDefault();
				string text = " - ";
				string text2 = " - ";
				if (protocolRequestModel2 != null)
				{
					if (protocolInput.autoGeneratedSchema)
					{
						text2 = $"{priority}";
					}
					else
					{
						text = $"{priority}";
					}
				}
				Paragraph val21 = MakeParagraph(text, (ParagraphAlignment)1, 10, 1, 1);
				Paragraph val22 = MakeParagraph(columns[num2].RuVal + " / " + columns[num2].EnVal, (ParagraphAlignment)0, 10, 1, 1);
				Paragraph val23 = MakeParagraph(text2, (ParagraphAlignment)1, 10, 1, 1);
				val20[0].Add(val21);
				val20[1].Add(val22);
				val20[2].Add(val23);
				if (protocolRequestModel2 != null)
				{
					val20.Cells[0].Shading.Color = Colors.PaleGoldenrod;
					val20.Cells[1].Shading.Color = Colors.PaleGoldenrod;
					val20.Cells[2].Shading.Color = Colors.PaleGoldenrod;
				}
				val20.Cells[0].VerticalAlignment = (VerticalAlignment)1;
				val20.Cells[1].VerticalAlignment = (VerticalAlignment)1;
				val20.Cells[2].VerticalAlignment = (VerticalAlignment)1;
			}
			for (int i2 = 0; i2 < protocolInput.protocolRequestModel.Count; i2++)
			{
				Section val24 = document.AddSection();
				if (i2 == 0)
				{
					Paragraph val25 = MakeParagraph("Последние просматриваемые графики параметров приоритетов", (ParagraphAlignment)1, 12, 10, 10);
					val24.Add(val25);
				}
				Table val26 = val24.AddTable();
				val26.Rows.Alignment = (RowAlignment)1;
				val26.AddColumn("16cm");
				Row val27 = val26.AddRow();
				val27.Borders.Width = 0.75;
				val27.Cells[0].Add(MakeParagraph(protocolInput.protocolRequestModel[i2].ChartLabel, (ParagraphAlignment)1, 10, 4, 4));
				Row table9row2 = val26.AddRow();
				Image val28 = await CreateImage(files[i2], "16cm");
				table9row2.Cells[0].Add(val28);
				table9row2.Borders.Width = 0.75;
			}
			List<List<(string, string, int)>> list = Fetch(selections);
			Section val29 = document.AddSection();
			int num3 = 0;
			for (int num4 = 0; num4 < list.Count; num4++)
			{
				num3 = 4 + num4;
				Paragraph val30 = MakeParagraph($"Таблица {4 + num4} - Вид и количестов компонентов, имеющих приоритет «{num4 + 1}»:", (ParagraphAlignment)0, 12, 8, 30);
				val29.Add(val30);
				Table val31 = val29.AddTable();
				val31.Borders.Visible = true;
				val31.Rows.Alignment = (RowAlignment)1;
				val31.AddColumn("7cm");
				val31.AddColumn("6cm");
				val31.AddColumn("3cm");
				Row val32 = val31.AddRow();
				val32.Cells[0].Add(MakeParagraph("Производитель", (ParagraphAlignment)1, 10, 1, 1));
				val32.Cells[1].Add(MakeParagraph("Вид компонента", (ParagraphAlignment)1, 10, 1, 1));
				val32.Cells[2].Add(MakeParagraph("Количество", (ParagraphAlignment)1, 10, 1, 1));
				val32.Cells[0].VerticalAlignment = (VerticalAlignment)1;
				val32.Cells[1].VerticalAlignment = (VerticalAlignment)1;
				val32.Cells[2].VerticalAlignment = (VerticalAlignment)1;
				int num5 = 0;
				foreach (var item4 in list[num4])
				{
					num5 += item4.Item3;
					Row val33 = val31.AddRow();
					val33.Cells[0].Add(MakeParagraph(item4.Item2, (ParagraphAlignment)1, 10, 1, 1));
					val33.Cells[1].Add(MakeParagraph(item4.Item1, (ParagraphAlignment)1, 10, 1, 1));
					val33.Cells[2].Add(MakeParagraph(item4.Item3.ToString(), (ParagraphAlignment)1, 10, 1, 1));
					val33.Cells[0].VerticalAlignment = (VerticalAlignment)1;
					val33.Cells[1].VerticalAlignment = (VerticalAlignment)1;
					val33.Cells[2].VerticalAlignment = (VerticalAlignment)1;
				}
				Paragraph val34 = MakeParagraph($"Число компонентов, имеющих значение (вид, производителя) приоритет «{num4 + 1}»: {num5} штук", (ParagraphAlignment)0, 12, 8, 8);
				val29.Add(val34);
			}
			Section val35 = document.AddSection();
			Paragraph val36 = MakeParagraph($"Таблица {num3 + 1} - Перечень выбранных компонентов", (ParagraphAlignment)0, 12, 12, 12);
			val35.Add(val36);
			KeyValuePair<string, List<Dictionary<string, object>>> keyValuePair = selections.Last();
			int count = keyValuePair.Value.Count;
			int num6 = 3;
			int num7 = 0;
			Table val37 = null;
			List<int> list2 = new List<int>();
			int index = columns.FindIndex((AliasModel aliasModel) => aliasModel.EnVal.ToLower() == "componentname");
			AliasModel value = columns.Find((AliasModel aliasModel) => aliasModel.EnVal.ToLower() == "componentname");
			AliasModel value2 = columns.First();
			columns[0] = value;
			columns[index] = value2;
			int orderIndex = 0;
			for (int num8 = 0; num8 < count;)
			{
				if (num7 == 0)
				{
					val37 = val35.AddTable();
					Paragraph val38 = val35.AddParagraph();
					val38.Format.SpaceBefore = "2cm";
					val37.Rows.Alignment = (RowAlignment)0;
					val37.Borders.Visible = true;
					val37.Borders.Width = 0.5;
					val37.AddColumn("4cm");
				}
				num7++;
				list2.Add(num8);
				if (num7 != num6 && num8 != count - 1)
				{
					continue;
				}
				foreach (int item5 in list2)
				{
					_ = item5;
					val37.AddColumn("4cm");
				}
				for (int num9 = 0; num9 < columns.Count(); num9++)
				{
					Row val39 = val37.AddRow();
					val39.Cells[0].Add(MakeParagraph(columns[num9].RuVal + " / " + columns[num9].EnVal, (ParagraphAlignment)1, 10, 1, 1));
					val39.Cells[0].VerticalAlignment = (VerticalAlignment)1;
					foreach (var item6 in list2.Select((int itter, int item2) => (itter: itter, index: item2)))
					{
						_ = item6.itter;
						int item = item6.index;
						if(item + num8 >= keyValuePair.Value.Count)
						{
							continue;
						}
						Dictionary<string, object> dictionary2 = keyValuePair.Value[item + num8];
						object obj2 = null;
						foreach (string key in dictionary2.Keys)
						{
							if (key.ToLower() == columns[num9].EnVal.ToLower())
							{
								obj2 = dictionary2[key];
								if (obj2 is DateTime dateTime)
								{
									obj2 = dateTime.ToString("yyyy-MM-dd");
								}
								break;
							}
						}
						val39.Cells[item + 1].Add(MakeParagraph($"{obj2}".IsNullOrEmpty() || $"{obj2}" == "null" ? "Не указано" : $"{obj2}", (ParagraphAlignment)1, 10, 1, 1));
						val39.Cells[item + 1].VerticalAlignment = (VerticalAlignment)1;
					}
					if (num9 == 0)
					{
						for (int num10 = 0; num10 <= num7; num10++)
						{
							val39.Cells[num10].Shading.Color = Colors.LightBlue;
						}
					}
				}
				num8 += 3;
				num7 = 0;
				list2.Clear();
			}
			return document;
		}
		private List<List<(string ruComponentKind, string manufacturerName, int amount)>> Fetch(
			Dictionary<string, List<Dictionary<string, object>>> selections)
		{
			var res = new List<List<(string ruComponentKind, string manufacturerName, int amount)>>();

			foreach (var key in selections.Keys)
			{
				var records = new List<(string ruComponentKind, string manufacturerName, int amount)>();
				var components = selections[key];
				var counter = new Dictionary<(string ruComponentKind, string manufacturerName), int>();

				foreach (var item in components)
				{
					string manufacturerName = item["ManufacturerName"] as string ?? "";
					string ruComponentKind = item["RuComponentKind"] as string ?? "";

					var tupleKey = (ruComponentKind, manufacturerName);

					if (!counter.ContainsKey(tupleKey))
						counter[tupleKey] = 0;

					counter[tupleKey]++;
				}

				foreach (var kvp in counter)
				{
					records.Add((kvp.Key.ruComponentKind, kvp.Key.manufacturerName, kvp.Value));
				}

				res.Add(records);
			}

			return res;
		}

		private async Task<Image> CreateImage(IFormFile file, string width)
		{
			using var stream = new MemoryStream();
			await file.CopyToAsync(stream);
			stream.Position = 0;

			var tempPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString() + Path.GetExtension(file.FileName));
			await File.WriteAllBytesAsync(tempPath, stream.ToArray());

			var image = new Image(tempPath);
			image.LockAspectRatio = true;
			image.Width = width;
			image.Top = ShapePosition.Top;
			image.Left = ShapePosition.Center;

			return image;
		}

		private Paragraph MakeParagraph(string text, ParagraphAlignment alignment, int fontsize, int spaceAfterPt, int spaceBeforePt, bool isBold = false)
		{
			Paragraph paragraph = new Paragraph();
			paragraph.AddFormattedText(text);
			paragraph.Format.Alignment = alignment;
			paragraph.Format.Font.Size = fontsize;
			paragraph.Format.Font.Bold = isBold;
			paragraph.Format.SpaceAfter = $"{spaceAfterPt}pt";
			paragraph.Format.SpaceBefore= $"{spaceBeforePt}pt";
			paragraph.Format.LeftIndent = 1;
			paragraph.Format.RightIndent = 1;
			return paragraph;
		}
	}
}
