

using app.Db.ef;
using app.Db.utils;
using app.Services.Common.Ref;
using app.Services.Component;
using app.Services.Component.component;
using app.Services.ComponentType;
using app.Services.PdfReport;
using app.Services.PdfReport;
using app.Services.PdfReport.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Shapes;
using MigraDoc.Rendering;
using System.Text.Json;
namespace WebAPIApp.Controllers
{
	[ApiController]
	[Route("[controller]")]
	public class ReportController : ControllerBase
	{
		readonly IPdfReportService _pdfReportService;
		readonly IComponentTypeService _componentTypeService;
		readonly IComponentService _componentService;
		readonly IRefHelper _refHelperService;
		readonly IMemoryCache _cache;

		public ReportController(IPdfReportService pdfReportService, IComponentTypeService componentTypeService, IComponentService componentService, IRefHelper refHelperService, IMemoryCache cache)
		{
			_pdfReportService = pdfReportService;
			_componentTypeService = componentTypeService;
			_componentService = componentService;
			_refHelperService = refHelperService;
			_cache = cache;
		}


		[HttpPost("{entype}/pdf")]
		public async Task<ActionResult> MakeReport(
			string entype,
			[FromForm] IFormFileCollection files,
			[FromForm] string reports,
			[FromForm] bool autoGeneratedSchema
		)
		{
			entype = entype.ToLower();
			_cache.TryGetValue("components/names", out List<ComponentTypes> names);
			if (names == null)
			{
				names = await _componentTypeService.SelectAll();
				_cache.Set("components/names", names, new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromHours(1)));
			}
			var isEntypeExists = names.ExistEnType(entype);
			_cache.TryGetValue("components/all", out DataSystemView all);
			if (all == null)
			{
				all = await _componentService.SelectAll();
				_cache.Set("components/all", all, new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromHours(1)));
			}
			var columns = await _refHelperService.GetAllMapedColumns(entype);
			if (columns == null)
			{
				return BadRequest();
			}
			var reportList = JsonSerializer.Deserialize<List<ProtocolRequestModel>>(reports);
			Dictionary<string, string> parameters = new();
			foreach (var item in reportList)
			{
				parameters[item.ParameterName] = item.ParameterValue;
			}

			var components = all.GetComponentsByEnType(entype);
			var selections = components.GetStepSelection(parameters);
			var componentType = names.Find(name => name.EnComponentType.ToLower() == entype.ToLower());
			//List<IComponentModel> components = await _componentService.GetComponentsByEnType(entype);
			//var prComponents = await _componentService.GetPriorityComponents(components, entype, parameters);
			//ComponentAllModel componentAllModel = await _componentService.

			//var selections = prComponents[entype];

			//if (report.Components == null)


			Document doc = await _pdfReportService.CreateDocReport((reportList, autoGeneratedSchema), selections, files, columns, componentType.RuComponentType);
			PdfDocumentRenderer renderer = new PdfDocumentRenderer();

			renderer.Document = doc;
			renderer.RenderDocument();

			using (var stream = new MemoryStream())
			{
				renderer.PdfDocument.Save(stream, false);
				stream.Position = 0;
				return File(stream.ToArray(), "application/pdf", "report.pdf");
			}
		}

	}
}